# docker-compose.yml
# We should let the IP address fixed, because the DNS do not work correctly when joining L1 nodes
version: '3'
services:
  l1-data-1:
    container_name: l1-data-1
    build:
      context: ../../../source
      dockerfile: ../infra/docker/metagraph-l1-data/initial-validator/Dockerfile
    image: metagraph-l1-data-initial-validator
    environment:
      - CL_PUBLIC_HTTP_PORT=9000
      - CL_P2P_HTTP_PORT=9001
      - CL_CLI_HTTP_PORT=9002
      - CL_L0_PEER_HTTP_HOST=l0-currency-1
      - CL_L0_PEER_HTTP_PORT=9000
      - CL_GLOBAL_L0_PEER_HTTP_HOST=l0-global
      - CL_GLOBAL_L0_PEER_HTTP_PORT=9000
      - CL_APP_ENV=dev
      - CL_COLLATERAL=0
    volumes:
      - ../shared/jars:/code/jars/
    ports:
      - '8000:9000'
      - '8001:9001'
      - '8002:9002'
    networks:
      custom-network:
        ipv4_address: 172.50.0.40
    command: >
      sh -c "export CL_GLOBAL_L0_PEER_ID=$$(java -jar cl-wallet.jar show-id) && \
             export CL_L0_PEER_ID=$${CL_GLOBAL_L0_PEER_ID}
             export CL_L0_TOKEN_IDENTIFIER=$METAGRAPH_ID && \
             cp metagraph-l1-data.jar jars/metagraph-l1-data.jar && \
             cp cl-wallet.jar jars/cl-wallet.jar && \
             java -jar metagraph-l1-data.jar run-initial-validator --ip 172.50.0.40"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://l1-data-1:9000/cluster/info" ]
      interval: 10s
      timeout: 10s
      retries: 10
  l1-data-2:
    container_name: l1-data-2
    build:
      context: ../../../source
      dockerfile: ../infra/docker/metagraph-l1-data/node-2/Dockerfile
    image: metagraph-l1-data-validator-node-2
    depends_on:
      l1-data-1:
        condition: service_healthy
    environment:
      - CL_PUBLIC_HTTP_PORT=9000
      - CL_P2P_HTTP_PORT=9001
      - CL_CLI_HTTP_PORT=9002
      - CL_L0_PEER_HTTP_HOST=l0-currency-1
      - CL_L0_PEER_HTTP_PORT=9000
      - CL_GLOBAL_L0_PEER_HTTP_HOST=l0-global
      - CL_GLOBAL_L0_PEER_HTTP_PORT=9000
      - CL_APP_ENV=dev
      - CL_COLLATERAL=0
    volumes:
      - ../shared/jars:/code/jars/
    ports:
      - '8100:9000'
      - '8101:9001'
      - '8102:9002'
    networks:
      custom-network:
        ipv4_address: 172.50.0.41
    command: >
      sh -c "cp jars/cl-wallet.jar genesis/cl-wallet.jar && \
      
             cd genesis/ && \
      
             export CL_KEYSTORE=$${CL_KEYSTORE_GENESIS} && \
             export CL_KEYALIAS=$${CL_KEYALIAS_GENESIS} && \
             export CL_PASSWORD=$${CL_PASSWORD_GENESIS} && \
      
             export CL_GLOBAL_L0_PEER_ID=$$(java -jar cl-wallet.jar show-id) && \
             export CL_L0_PEER_ID=$${CL_GLOBAL_L0_PEER_ID}
             export CL_L0_TOKEN_IDENTIFIER=$METAGRAPH_ID && \
      
             cd ../ && \
      
             export CL_KEYSTORE=$${CL_KEYSTORE_NODE_2} && \
             export CL_KEYALIAS=$${CL_KEYALIAS_NODE_2} && \
             export CL_PASSWORD=$${CL_PASSWORD_NODE_2} && \
      
             cp jars/metagraph-l1-data.jar metagraph-l1-data.jar && \
             java -jar metagraph-l1-data.jar run-validator --ip 172.50.0.41"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://l1-data-2:9000/metrics" ]
      interval: 10s
      timeout: 10s
      retries: 10
  l1-data-3:
    container_name: l1-data-3
    build:
      context: ../../../source
      dockerfile: ../infra/docker/metagraph-l1-data/node-3/Dockerfile
    image: metagraph-l1-data-validator-node-3
    depends_on:
      l1-data-1:
        condition: service_healthy
    environment:
      - CL_PUBLIC_HTTP_PORT=9000
      - CL_P2P_HTTP_PORT=9001
      - CL_CLI_HTTP_PORT=9002
      - CL_L0_PEER_HTTP_HOST=l0-currency-1
      - CL_L0_PEER_HTTP_PORT=9000
      - CL_GLOBAL_L0_PEER_HTTP_HOST=l0-global
      - CL_GLOBAL_L0_PEER_HTTP_PORT=9000
      - CL_APP_ENV=dev
      - CL_COLLATERAL=0
    volumes:
      - ../shared/jars:/code/jars/
    ports:
      - '8200:9000'
      - '8201:9001'
      - '8202:9002'
    networks:
      custom-network:
        ipv4_address: 172.50.0.42
    command: >
      sh -c "cp jars/cl-wallet.jar genesis/cl-wallet.jar && \

             cd genesis/ && \

             export CL_KEYSTORE=$${CL_KEYSTORE_GENESIS} && \
             export CL_KEYALIAS=$${CL_KEYALIAS_GENESIS} && \
             export CL_PASSWORD=$${CL_PASSWORD_GENESIS} && \

             export CL_GLOBAL_L0_PEER_ID=$$(java -jar cl-wallet.jar show-id) && \
             export CL_L0_PEER_ID=$${CL_GLOBAL_L0_PEER_ID}
             export CL_L0_TOKEN_IDENTIFIER=$METAGRAPH_ID && \

             cd ../ && \

             export CL_KEYSTORE=$${CL_KEYSTORE_NODE_3} && \
             export CL_KEYALIAS=$${CL_KEYALIAS_NODE_3} && \
             export CL_PASSWORD=$${CL_PASSWORD_NODE_3} && \

             cp jars/metagraph-l1-data.jar metagraph-l1-data.jar && \
             java -jar metagraph-l1-data.jar run-validator --ip 172.50.0.42"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://l1-data-3:9000/metrics" ]
      interval: 10s
      timeout: 10s
      retries: 10
networks:
  custom-network:
    external: true