global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
  - job_name: dynamic-targets
    http_sd_configs:
      - url: http://172.50.0.5:9000/targets
      - url: http://172.50.0.10:9000/targets
      - url: http://172.50.0.11:9000/targets
      - url: http://172.50.0.12:9000/targets
      - url: http://172.50.0.20:9000/targets
      - url: http://172.50.0.21:9000/targets
      - url: http://172.50.0.22:9000/targets
      - url: http://172.50.0.30:9000/targets
      - url: http://172.50.0.31:9000/targets
      - url: http://172.50.0.32:9000/targets