# docker-compose.yml
# We should let the IP address fixed, because the DNS do not work correctly when joining L1 nodes
version: '3'
services:
  l1-currency-1:
    container_name: l1-currency-1
    build:
      context: ../../../source
      dockerfile: ../infra/docker/metagraph-l1-currency/initial-validator/Dockerfile
    image: metagraph-l1-currency-initial-validator
    environment:
      - CL_PUBLIC_HTTP_PORT=9000
      - CL_P2P_HTTP_PORT=9001
      - CL_CLI_HTTP_PORT=9002
      - CL_L0_PEER_HTTP_HOST=l0-currency-1
      - CL_L0_PEER_HTTP_PORT=9000
      - CL_GLOBAL_L0_PEER_HTTP_HOST=l0-global
      - CL_GLOBAL_L0_PEER_HTTP_PORT=9000
      - CL_APP_ENV=dev
      - CL_COLLATERAL=0
    volumes:
      - ../shared/jars:/code/jars/
    ports:
      - '9700:9000'
      - '9701:9001'
      - '9702:9002'
    networks:
      custom-network:
        ipv4_address: 172.50.0.30
    command: >
      sh -c "export CL_GLOBAL_L0_PEER_ID=$$(java -jar cl-wallet.jar show-id) && \
             export CL_L0_PEER_ID=$${CL_GLOBAL_L0_PEER_ID}
             export CL_L0_TOKEN_IDENTIFIER=$METAGRAPH_ID && \
             cp metagraph-l1-currency.jar jars/metagraph-l1-currency.jar && \
             cp cl-wallet.jar jars/cl-wallet.jar && \
             java -jar metagraph-l1-currency.jar run-initial-validator --ip 172.50.0.30"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://l1-currency-1:9000/cluster/info" ]
      interval: 10s
      timeout: 10s
      retries: 10
  l1-currency-2:
    container_name: l1-currency-2
    build:
      context: ../../../source
      dockerfile: ../infra/docker/metagraph-l1-currency/node-2/Dockerfile
    image: metagraph-l1-currency-validator-node-2
    depends_on:
      l1-currency-1:
        condition: service_healthy
    environment:
      - CL_PUBLIC_HTTP_PORT=9000
      - CL_P2P_HTTP_PORT=9001
      - CL_CLI_HTTP_PORT=9002
      - CL_L0_PEER_HTTP_HOST=l0-currency-1
      - CL_L0_PEER_HTTP_PORT=9000
      - CL_GLOBAL_L0_PEER_HTTP_HOST=l0-global
      - CL_GLOBAL_L0_PEER_HTTP_PORT=9000
      - CL_APP_ENV=dev
      - CL_COLLATERAL=0
    volumes:
      - ../shared/jars:/code/jars/
    ports:
      - '9800:9000'
      - '9801:9001'
      - '9802:9002'
    networks:
      custom-network:
        ipv4_address: 172.50.0.31
    command: >
      sh -c "cp jars/cl-wallet.jar genesis/cl-wallet.jar && \
      
             cd genesis/ && \
      
             export CL_KEYSTORE=$${CL_KEYSTORE_GENESIS} && \
             export CL_KEYALIAS=$${CL_KEYALIAS_GENESIS} && \
             export CL_PASSWORD=$${CL_PASSWORD_GENESIS} && \
      
             export CL_GLOBAL_L0_PEER_ID=$$(java -jar cl-wallet.jar show-id) && \
             export CL_L0_PEER_ID=$${CL_GLOBAL_L0_PEER_ID}
             export CL_L0_TOKEN_IDENTIFIER=$METAGRAPH_ID && \
      
             cd ../ && \
      
             export CL_KEYSTORE=$${CL_KEYSTORE_NODE_2} && \
             export CL_KEYALIAS=$${CL_KEYALIAS_NODE_2} && \
             export CL_PASSWORD=$${CL_PASSWORD_NODE_2} && \
      
             cp jars/metagraph-l1-currency.jar metagraph-l1-currency.jar && \
             java -jar metagraph-l1-currency.jar run-validator --ip 172.50.0.31"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://l1-currency-2:9000/metrics" ]
      interval: 10s
      timeout: 10s
      retries: 10
  l1-currency-3:
    container_name: l1-currency-3
    build:
      context: ../../../source
      dockerfile: ../infra/docker/metagraph-l1-currency/node-3/Dockerfile
    image: metagraph-l1-currency-validator-node-3
    depends_on:
      l1-currency-1:
        condition: service_healthy
    environment:
      - CL_PUBLIC_HTTP_PORT=9000
      - CL_P2P_HTTP_PORT=9001
      - CL_CLI_HTTP_PORT=9002
      - CL_L0_PEER_HTTP_HOST=l0-currency-1
      - CL_L0_PEER_HTTP_PORT=9000
      - CL_GLOBAL_L0_PEER_HTTP_HOST=l0-global
      - CL_GLOBAL_L0_PEER_HTTP_PORT=9000
      - CL_APP_ENV=dev
      - CL_COLLATERAL=0
    volumes:
      - ../shared/jars:/code/jars/
    ports:
      - '9900:9000'
      - '9901:9001'
      - '9902:9002'
    networks:
      custom-network:
        ipv4_address: 172.50.0.32
    command: >
      sh -c "cp jars/cl-wallet.jar genesis/cl-wallet.jar && \

             cd genesis/ && \

             export CL_KEYSTORE=$${CL_KEYSTORE_GENESIS} && \
             export CL_KEYALIAS=$${CL_KEYALIAS_GENESIS} && \
             export CL_PASSWORD=$${CL_PASSWORD_GENESIS} && \

             export CL_GLOBAL_L0_PEER_ID=$$(java -jar cl-wallet.jar show-id) && \
             export CL_L0_PEER_ID=$${CL_GLOBAL_L0_PEER_ID}
             export CL_L0_TOKEN_IDENTIFIER=$METAGRAPH_ID && \

             cd ../ && \

             export CL_KEYSTORE=$${CL_KEYSTORE_NODE_3} && \
             export CL_KEYALIAS=$${CL_KEYALIAS_NODE_3} && \
             export CL_PASSWORD=$${CL_PASSWORD_NODE_3} && \

             cp jars/metagraph-l1-currency.jar metagraph-l1-currency.jar && \
             java -jar metagraph-l1-currency.jar run-validator --ip 172.50.0.32"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://l1-currency-3:9000/metrics" ]
      interval: 10s
      timeout: 10s
      retries: 10
networks:
  custom-network:
    external: true