# docker-compose.yml
# We should let the IP address fixed, because the DNS do not work correctly when joining L1 nodes
version: '3'
services:
  l0-global:
    container_name: l0-global
    build:
      context: ../../../source
      dockerfile: ../infra/docker/global-l0/Dockerfile
    image: global-l0
    environment:
      - CL_APP_ENV=dev
      - CL_COLLATERAL=0
      - CL_ENV=dev
      - SHOULD_RESET_GENESIS_FILE=${SHOULD_RESET_GENESIS_FILE}
    volumes:
      - ../shared/jars:/code/jars/
      - ../../../source/global-l0/tessellation:/code/codebase/tessellation
      - ../../../source/global-l0/genesis:/code/genesis/
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      custom-network:
        ipv4_address: 172.50.0.2
    command: >
      sh -c 'cp genesis/genesis.csv genesis.csv && \
             cp global-l0.jar jars/ && \
             cp cl-keytool.jar jars/ && \
             cp cl-wallet.jar jars/ && \
             [ -d data/ ] && rm -r data && java -jar global-l0.jar run-genesis genesis.csv --ip 172.50.0.2 || \
             java -jar global-l0.jar run-genesis genesis.csv --ip 172.50.0.2'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://l0-global:9000/cluster/info" ]
      interval: 10s
      timeout: 10s
      retries: 10
networks:
  custom-network:
    external: true